inherit: 
    - base.yaml

model:
    family: gpt2
    n_dims: 20
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_positions: 201

training:
    task: linear_regression
    data: gaussian
    task_kwargs: 
        random_cov: true   # New flag to enable random covariance
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    train_steps: 500001
    curriculum:
        points:
            start: 40  # Can be changed to 70 or 100 
            end: 40    # Same as start
            inc: 0     # No increment
            interval: 2000
        dims:
            start: 20
            end: 20
            inc: 0
            interval: 2000

out_dir: ../models/random_cov

wandb:
    name: "random_cov_standard"